 if :def:song__CARIBBEAN_DEF 
 include song__CARIBBEAN.asm 
 endif 
 
 if :def:song__HAWAIIAN_DEF 
 include song__HAWAIIAN.asm 
 endif 
 
 if :def:song__INDONESIAN_DEF 
 include song__INDONESIAN.asm 
 endif 
 
 if :def:song__LATIN_DEF 
 include song__LATIN.asm 
 endif 
 
 if :def:song__LATINFOLK_DEF 
 include song__LATINFOLK.asm 
 endif 
 
 if :def:song_AIAI_DEF 
 include song_AIAI.asm 
 endif 
 
 if :def:song_AKATONBO_DEF 
 include song_AKATONBO.asm 
 endif 
 
 if :def:song_ALOHAOE3_DEF 
 include song_ALOHAOE3.asm 
 endif 
 
 if :def:song_AMAZING_DEF 
 include song_AMAZING.asm 
 endif 
 
 if :def:song_AMEFURI_DEF 
 include song_AMEFURI.asm 
 endif 
 
 if :def:song_AMEKUMA_DEF 
 include song_AMEKUMA.asm 
 endif 
 
 if :def:song_AMETSUKI_DEF 
 include song_AMETSUKI.asm 
 endif 
 
 if :def:song_ANNI_DEF 
 include song_ANNI.asm 
 endif 
 
 if :def:song_ANPANMARCH_DEF 
 include song_ANPANMARCH.asm 
 endif 
 
 if :def:song_ANPANTAISO_DEF 
 include song_ANPANTAISO.asm 
 endif 
 
 if :def:song_AOIMENO_DEF 
 include song_AOIMENO.asm 
 endif 
 
 if :def:song_ARIA_DEF 
 include song_ARIA.asm 
 endif 
 
 if :def:song_AU_DEF 
 include song_AU.asm 
 endif 
 
 if :def:song_AWATENBOU_DEF 
 include song_AWATENBOU.asm 
 endif 
 
 if :def:song_AWATETOKOYA_DEF 
 include song_AWATETOKOYA.asm 
 endif 
 
 if :def:song_AWAY_DEF 
 include song_AWAY.asm 
 endif 
 
 if :def:song_BAMBA_DEF 
 include song_BAMBA.asm 
 endif 
 
 if :def:song_BANANABOAT_DEF 
 include song_BANANABOAT.asm 
 endif 
 
 if :def:song_BIRTHDAY_DEF 
 include song_BIRTHDAY.asm 
 endif 
 
 if :def:song_BIWAKO_DEF 
 include song_BIWAKO.asm 
 endif 
 
 if :def:song_BOLERO_DEF 
 include song_BOLERO.asm 
 endif 
 
 if :def:song_BRAHMS_DEF 
 include song_BRAHMS.asm 
 endif 
 
 if :def:song_BROWNJUG3_DEF 
 include song_BROWNJUG3.asm 
 endif 
 
 if :def:song_BUNBUNBUN_DEF 
 include song_BUNBUNBUN.asm 
 endif 
 
 if :def:song_CAMARADE_DEF 
 include song_CAMARADE.asm 
 endif 
 
 if :def:song_CHIGUSA_DEF 
 include song_CHIGUSA.asm 
 endif 
 
 if :def:song_CHOUCHOU_DEF 
 include song_CHOUCHOU.asm 
 endif 
 
 if :def:song_CHUURIPPU_DEF 
 include song_CHUURIPPU.asm 
 endif 
 
 if :def:song_CIELITOLINDO_DEF 
 include song_CIELITOLINDO.asm 
 endif 
 
 if :def:song_CLEMENTINE_DEF 
 include song_CLEMENTINE.asm 
 endif 
 
 if :def:song_COFFEERUMBA_DEF 
 include song_COFFEERUMBA.asm 
 endif 
 
 if :def:song_CONDOR_DEF 
 include song_CONDOR.asm 
 endif 
 
 if :def:song_DECKTHEHALL_DEF 
 include song_DECKTHEHALL.asm 
 endif 
 
 if :def:song_DENDEN_DEF 
 include song_DENDEN.asm 
 endif 
 
 if :def:song_DERRY_DEF 
 include song_DERRY.asm 
 endif 
 
 if :def:song_DONGURI_DEF 
 include song_DONGURI.asm 
 endif 
 
 if :def:song_DONGURI3_DEF 
 include song_DONGURI3.asm 
 endif 
 
 if :def:song_DOREMIFAAPM_DEF 
 include song_DOREMIFAAPM.asm 
 endif 
 
 if :def:song_DREAMER_DEF 
 include song_DREAMER.asm 
 endif 
 
 if :def:song_ELECTRICAL_DEF 
 include song_ELECTRICAL.asm 
 endif 
 
 if :def:song_FURUDOKEI_DEF 
 include song_FURUDOKEI.asm 
 endif 
 
 if :def:song_FURUSATO_DEF 
 include song_FURUSATO.asm 
 endif 
 
 if :def:song_FURUSATO4_DEF 
 include song_FURUSATO4.asm 
 endif 
 
 if :def:song_FUYUGESHIKI_DEF 
 include song_FUYUGESHIKI.asm 
 endif 
 
 if :def:song_FUYUNOUTA_DEF 
 include song_FUYUNOUTA.asm 
 endif 
 
 if :def:song_FUYUNOYORU_DEF 
 include song_FUYUNOYORU.asm 
 endif 
 
 if :def:song_GENKOTU_DEF 
 include song_GENKOTU.asm 
 endif 
 
 if :def:song_GOGATSUMURA_DEF 
 include song_GOGATSUMURA.asm 
 endif 
 
 if :def:song_GOLONDRINA_DEF 
 include song_GOLONDRINA.asm 
 endif 
 
 if :def:song_GONDOLA_DEF 
 include song_GONDOLA.asm 
 endif 
 
 if :def:song_HALELUYA_DEF 
 include song_HALELUYA.asm 
 endif 
 
 if :def:song_HAMABE_DEF 
 include song_HAMABE.asm 
 endif 
 
 if :def:song_HANA_DEF 
 include song_HANA.asm 
 endif 
 
 if :def:song_HARUKITA_DEF 
 include song_HARUKITA.asm 
 endif 
 
 if :def:song_HARUKOI_DEF 
 include song_HARUKOI.asm 
 endif 
 
 if :def:song_HARUOGAWA_DEF 
 include song_HARUOGAWA.asm 
 endif 
 
 if :def:song_HEIGH_HO_DEF 
 include song_HEIGH_HO.asm 
 endif 
 
 if :def:song_HINAMATSURI_DEF 
 include song_HINAMATSURI.asm 
 endif 
 
 if :def:song_HOLDIRIDIA_DEF 
 include song_HOLDIRIDIA.asm 
 endif 
 
 if :def:song_HOME_DEF 
 include song_HOME.asm 
 endif 
 
 if :def:song_HOSINEGAI_DEF 
 include song_HOSINEGAI.asm 
 endif 
 
 if :def:song_HOSISEKAI_DEF 
 include song_HOSISEKAI.asm 
 endif 
 
 if :def:song_HOTARUHIKARI3_DEF 
 include song_HOTARUHIKARI3.asm 
 endif 
 
 if :def:song_ICHIGATSU_DEF 
 include song_ICHIGATSU.asm 
 endif 
 
 if :def:song_IFUDODO_DEF 
 include song_IFUDODO.asm 
 endif 
 
 if :def:song_INUOMAWARI_DEF 
 include song_INUOMAWARI.asm 
 endif 
 
 if :def:song_ISSYUUKAN_DEF 
 include song_ISSYUUKAN.asm 
 endif 
 
 if :def:song_ITOMAKI_DEF 
 include song_ITOMAKI.asm 
 endif 
 
 if :def:song_JAMAICA_DEF 
 include song_JAMAICA.asm 
 endif 
 
 if :def:song_JINGLE_DEF 
 include song_JINGLE.asm 
 endif 
 
 if :def:song_JUPITER_DEF 
 include song_JUPITER.asm 
 endif 
 
 if :def:song_KAERUGASSHOU_DEF 
 include song_KAERUGASSHOU.asm 
 endif 
 
 if :def:song_KANASHIMINO_DEF 
 include song_KANASHIMINO.asm 
 endif 
 
 if :def:song_KANON_DEF 
 include song_KANON.asm 
 endif 
 
 if :def:song_KARATACHI_DEF 
 include song_KARATACHI.asm 
 endif 
 
 if :def:song_KARINKA_DEF 
 include song_KARINKA.asm 
 endif 
 
 if :def:song_KATYUSHA_DEF 
 include song_KATYUSHA.asm 
 endif 
 
 if :def:song_KAWAIANOKO_DEF 
 include song_KAWAIANOKO.asm 
 endif 
 
 if :def:song_KENTUCKY_DEF 
 include song_KENTUCKY.asm 
 endif 
 
 if :def:song_KIRAKIRABOSI_DEF 
 include song_KIRAKIRABOSI.asm 
 endif 
 
 if :def:song_KISYA_DEF 
 include song_KISYA.asm 
 endif 
 
 if :def:song_KISYAPOPO_DEF 
 include song_KISYAPOPO.asm 
 endif 
 
 if :def:song_KITTY_DEF 
 include song_KITTY.asm 
 endif 
 
 if :def:song_KODOMOTO_DEF 
 include song_KODOMOTO.asm 
 endif 
 
 if :def:song_KOHAN_DEF 
 include song_KOHAN.asm 
 endif 
 
 if :def:song_KOINOBORI3_DEF 
 include song_KOINOBORI3.asm 
 endif 
 
 if :def:song_KOKYONOSORA_DEF 
 include song_KOKYONOSORA.asm 
 endif 
 
 if :def:song_KUROIHITOMI_DEF 
 include song_KUROIHITOMI.asm 
 endif 
 
 if :def:song_KUTSUNARU_DEF 
 include song_KUTSUNARU.asm 
 endif 
 
 if :def:song_KYORO_DEF 
 include song_KYORO.asm 
 endif 
 
 if :def:song_MACHIBOUKE_DEF 
 include song_MACHIBOUKE.asm 
 endif 
 
 if :def:song_MAKIBAWA_DEF 
 include song_MAKIBAWA.asm 
 endif 
 
 if :def:song_MAMASOBA_DEF 
 include song_MAMASOBA.asm 
 endif 
 
 if :def:song_MATSUBARA_DEF 
 include song_MATSUBARA.asm 
 endif 
 
 if :def:song_MERIHITUJI_DEF 
 include song_MERIHITUJI.asm 
 endif 
 
 if :def:song_MICKY_DEF 
 include song_MICKY.asm 
 endif 
 
 if :def:song_MOMIJI_DEF 
 include song_MOMIJI.asm 
 endif 
 
 if :def:song_MOMOTARO_DEF 
 include song_MOMOTARO.asm 
 endif 
 
 if :def:song_MORIKUMA_DEF 
 include song_MORIKUMA.asm 
 endif 
 
 if :def:song_MUSIKOE_DEF 
 include song_MUSIKOE.asm 
 endif 
 
 if :def:song_MUSUNDE_DEF 
 include song_MUSUNDE.asm 
 endif 
 
 if :def:song_NANATSU_DEF 
 include song_NANATSU.asm 
 endif 
 
 if :def:song_NANATSU2_DEF 
 include song_NANATSU2.asm 
 endif 
 
 if :def:song_NATSUKINU_DEF 
 include song_NATSUKINU.asm 
 endif 
 
 if :def:song_NEKOHUN_DEF 
 include song_NEKOHUN.asm 
 endif 
 
 if :def:song_NEMURE_DEF 
 include song_NEMURE.asm 
 endif 
 
 if :def:song_NEMURE2_DEF 
 include song_NEMURE2.asm 
 endif 
 
 if :def:song_NOBARA_DEF 
 include song_NOBARA.asm 
 endif 
 
 if :def:song_OBENTOBAKO_DEF 
 include song_OBENTOBAKO.asm 
 endif 
 
 if :def:song_OBORO_DEF 
 include song_OBORO.asm 
 endif 
 
 if :def:song_ODOPON_DEF 
 include song_ODOPON.asm 
 endif 
 
 if :def:song_OKAASAN_DEF 
 include song_OKAASAN.asm 
 endif 
 
 if :def:song_ONCEINROYAL_DEF 
 include song_ONCEINROYAL.asm 
 endif 
 
 if :def:song_ONIPANTU_DEF 
 include song_ONIPANTU.asm 
 endif 
 
 if :def:song_ONMAHA_DEF 
 include song_ONMAHA.asm 
 endif 
 
 if :def:song_OOKINAKURI_DEF 
 include song_OOKINAKURI.asm 
 endif 
 
 if :def:song_OSHOGATSU_DEF 
 include song_OSHOGATSU.asm 
 endif 
 
 if :def:song_OSHOGATSU3_DEF 
 include song_OSHOGATSU3.asm 
 endif 
 
 if :def:song_OTUKAIARISAN_DEF 
 include song_OTUKAIARISAN.asm 
 endif 
 
 if :def:song_PECHKA_DEF 
 include song_PECHKA.asm 
 endif 
 
 if :def:song_PICNIC_DEF 
 include song_PICNIC.asm 
 endif 
 
 if :def:song_PONYO_DEF 
 include song_PONYO.asm 
 endif 
 
 if :def:song_RAILWAY_DEF 
 include song_RAILWAY.asm 
 endif 
 
 if :def:song_REPUBLIC_DEF 
 include song_REPUBLIC.asm 
 endif 
 
 if :def:song_ROMANCE_DEF 
 include song_ROMANCE.asm 
 endif 
 
 if :def:song_RYOSHU_DEF 
 include song_RYOSHU.asm 
 endif 
 
 if :def:song_SAINTS_DEF 
 include song_SAINTS.asm 
 endif 
 
 if :def:song_SAKURA2_DEF 
 include song_SAKURA2.asm 
 endif 
 
 if :def:song_SANPO_DEF 
 include song_SANPO.asm 
 endif 
 
 if :def:song_SANSAN_DEF 
 include song_SANSAN.asm 
 endif 
 
 if :def:song_SANTAMATI_DEF 
 include song_SANTAMATI.asm 
 endif 
 
 if :def:song_SAYAKANI_DEF 
 include song_SAYAKANI.asm 
 endif 
 
 if :def:song_SEIKURABE_DEF 
 include song_SEIKURABE.asm 
 endif 
 
 if :def:song_SENROWA_DEF 
 include song_SENROWA.asm 
 endif 
 
 if :def:song_SHOJOTANUKI_DEF 
 include song_SHOJOTANUKI.asm 
 endif 
 
 if :def:song_SIAWASENARA_DEF 
 include song_SIAWASENARA.asm 
 endif 
 
 if :def:song_SILENTNIGHT_DEF 
 include song_SILENTNIGHT.asm 
 endif 
 
 if :def:song_SILENTNIGHT3_DEF 
 include song_SILENTNIGHT3.asm 
 endif 
 
 if :def:song_SINJUGAI3_DEF 
 include song_SINJUGAI3.asm 
 endif 
 
 if :def:song_SINSEKAI4_DEF 
 include song_SINSEKAI4.asm 
 endif 
 
 if :def:song_SLEEVES_DEF 
 include song_SLEEVES.asm 
 endif 
 
 if :def:song_SMALLWORLD_DEF 
 include song_SMALLWORLD.asm 
 endif 
 
 if :def:song_SOUSYUNFU_DEF 
 include song_SOUSYUNFU.asm 
 endif 
 
 if :def:song_SYABONDAMA_DEF 
 include song_SYABONDAMA.asm 
 endif 
 
 if :def:song_TAKEDA_DEF 
 include song_TAKEDA.asm 
 endif 
 
 if :def:song_TAKIBI_DEF 
 include song_TAKIBI.asm 
 endif 
 
 if :def:song_TANABATA_DEF 
 include song_TANABATA.asm 
 endif 
 
 if :def:song_TEWOTATA_DEF 
 include song_TEWOTATA.asm 
 endif 
 
 if :def:song_THOMAS_DEF 
 include song_THOMAS.asm 
 endif 
 
 if :def:song_THOMAS2_DEF 
 include song_THOMAS2.asm 
 endif 
 
 if :def:song_TONTONHIGE_DEF 
 include song_TONTONHIGE.asm 
 endif 
 
 if :def:song_TOORIMICHI_DEF 
 include song_TOORIMICHI.asm 
 endif 
 
 if :def:song_TOTORO_DEF 
 include song_TOTORO.asm 
 endif 
 
 if :def:song_TRISTESSE_DEF 
 include song_TRISTESSE.asm 
 endif 
 
 if :def:song_TRISTESSE2_DEF 
 include song_TRISTESSE2.asm 
 endif 
 
 if :def:song_TROIKA_DEF 
 include song_TROIKA.asm 
 endif 
 
 if :def:song_UMI_DEF 
 include song_UMI.asm 
 endif 
 
 if :def:song_VRENELI_DEF 
 include song_VRENELI.asm 
 endif 
 
 if :def:song_WEWISH_DEF 
 include song_WEWISH.asm 
 endif 
 
 if :def:song_WINTERWONDER_DEF 
 include song_WINTERWONDER.asm 
 endif 
 
 if :def:song_YAMAONGAKUKA_DEF 
 include song_YAMAONGAKUKA.asm 
 endif 
 
 if :def:song_YOROKOBI4_DEF 
 include song_YOROKOBI4.asm 
 endif 
 
 if :def:song_YUKI_DEF 
 include song_YUKI.asm 
 endif 
 
 if :def:song_YURIKAGO_DEF 
 include song_YURIKAGO.asm 
 endif 
 
 if :def:song_YURIKAGO3_DEF 
 include song_YURIKAGO3.asm 
 endif 
 
 if :def:song_YUUKI100_DEF 
 include song_YUUKI100.asm 
 endif 
 
 if :def:song_YUUKIRINRIN_DEF 
 include song_YUUKIRINRIN.asm 
 endif 
 
 if :def:song_YUUYAKE_DEF 
 include song_YUUYAKE.asm 
 endif 
 
 if :def:song_ZOUSAN_DEF 
 include song_ZOUSAN.asm 
 endif 
 
 end
