del song.inc
del song.asm
call i.bat _CARIBBEAN
call i.bat _HAWAIIAN
call i.bat _INDONESIAN
call i.bat _LATIN
call i.bat _LATINFOLK
call i.bat AIAI
call i.bat AKATONBO
call i.bat ALOHAOE3
call i.bat AMAZING
call i.bat AMEFURI
call i.bat AMEKUMA
call i.bat AMETSUKI
call i.bat ANNI
call i.bat ANPANMARCH
call i.bat ANPANTAISO
call i.bat AOIMENO
call i.bat ARIA
call i.bat AU
call i.bat AWATENBOU
call i.bat AWATETOKOYA
call i.bat AWAY
call i.bat BAMBA
call i.bat BANANABOAT
call i.bat BIRTHDAY
call i.bat BIWAKO
call i.bat BOLERO
call i.bat BRAHMS
call i.bat BROWNJUG3
call i.bat BUNBUNBUN
call i.bat CAMARADE
call i.bat CHIGUSA
call i.bat CHOUCHOU
call i.bat CHUURIPPU
call i.bat CIELITOLINDO
call i.bat CLEMENTINE
call i.bat COFFEERUMBA
call i.bat CONDOR
call i.bat DECKTHEHALL
call i.bat DENDEN
call i.bat DERRY
call i.bat DONGURI
call i.bat DONGURI3
call i.bat DOREMIFAAPM
call i.bat DREAMER
call i.bat ELECTRICAL
call i.bat FURUDOKEI
call i.bat FURUSATO
call i.bat FURUSATO4
call i.bat FUYUGESHIKI
call i.bat FUYUNOUTA
call i.bat FUYUNOYORU
call i.bat GENKOTU
call i.bat GOGATSUMURA
call i.bat GOLONDRINA
call i.bat GONDOLA
call i.bat HALELUYA
call i.bat HAMABE
call i.bat HANA
call i.bat HARUKITA
call i.bat HARUKOI
call i.bat HARUOGAWA
call i.bat HEIGH_HO
call i.bat HINAMATSURI
call i.bat HOLDIRIDIA
call i.bat HOME
call i.bat HOSINEGAI
call i.bat HOSISEKAI
call i.bat HOTARUHIKARI3
call i.bat ICHIGATSU
call i.bat IFUDODO
call i.bat INUOMAWARI
call i.bat ISSYUUKAN
call i.bat ITOMAKI
call i.bat JAMAICA
call i.bat JINGLE
call i.bat JUPITER
call i.bat KAERUGASSHOU
call i.bat KANASHIMINO
call i.bat KANON
call i.bat KARATACHI
call i.bat KARINKA
call i.bat KATYUSHA
call i.bat KAWAIANOKO
call i.bat KENTUCKY
call i.bat KIRAKIRABOSI
call i.bat KISYA
call i.bat KISYAPOPO
call i.bat KITTY
call i.bat KODOMOTO
call i.bat KOHAN
call i.bat KOINOBORI3
call i.bat KOKYONOSORA
call i.bat KUROIHITOMI
call i.bat KUTSUNARU
call i.bat KYORO
call i.bat MACHIBOUKE
call i.bat MAKIBAWA
call i.bat MAMASOBA
call i.bat MATSUBARA
call i.bat MERIHITUJI
call i.bat MICKY
call i.bat MOMIJI
call i.bat MOMOTARO
call i.bat MORIKUMA
call i.bat MUSIKOE
call i.bat MUSUNDE
call i.bat NANATSU
call i.bat NANATSU2
call i.bat NATSUKINU
call i.bat NEKOHUN
call i.bat NEMURE
call i.bat NEMURE2
call i.bat NOBARA
call i.bat OBENTOBAKO
call i.bat OBORO
call i.bat ODOPON
call i.bat OKAASAN
call i.bat ONCEINROYAL
call i.bat ONIPANTU
call i.bat ONMAHA
call i.bat OOKINAKURI
call i.bat OSHOGATSU
call i.bat OSHOGATSU3
call i.bat OTUKAIARISAN
call i.bat PECHKA
call i.bat PICNIC
call i.bat PONYO
call i.bat RAILWAY
call i.bat REPUBLIC
call i.bat ROMANCE
call i.bat RYOSHU
call i.bat SAINTS
call i.bat SAKURA2
call i.bat SANPO
call i.bat SANSAN
call i.bat SANTAMATI
call i.bat SAYAKANI
call i.bat SEIKURABE
call i.bat SENROWA
call i.bat SHOJOTANUKI
call i.bat SIAWASENARA
call i.bat SILENTNIGHT
call i.bat SILENTNIGHT3
call i.bat SINJUGAI3
call i.bat SINSEKAI4
call i.bat SLEEVES
call i.bat SMALLWORLD
call i.bat SOUSYUNFU
call i.bat SYABONDAMA
call i.bat TAKEDA
call i.bat TAKIBI
call i.bat TANABATA
call i.bat TEWOTATA
call i.bat THOMAS
call i.bat THOMAS2
call i.bat TONTONHIGE
call i.bat TOORIMICHI
call i.bat TOTORO
call i.bat TRISTESSE
call i.bat TRISTESSE2
call i.bat TROIKA
call i.bat UMI
call i.bat VRENELI
call i.bat WEWISH
call i.bat WINTERWONDER
call i.bat YAMAONGAKUKA
call i.bat YOROKOBI4
call i.bat YUKI
call i.bat YURIKAGO
call i.bat YURIKAGO3
call i.bat YUUKI100
call i.bat YUUKIRINRIN
call i.bat YUUYAKE
call i.bat ZOUSAN
echo; end>> song.inc
pause
